nome = str(input('Digite seu nome: ')).strip()
lista = nome.split()
comp = (len(lista)-1)
print('Muito prazer!')
print('O seu primeiro nome é {}'.format(lista[0]))
print('O seu Ultimo nome é {}'.format(lista[comp]))
